import { useRouter, useState } from "next/router";
import { useContext } from "react";
import AppContext from "../../../components/AppContext";
import Navbar from "../../../components/Navbar";
import styles from "/styles/WatchPage.module.css";
import Head from "next/head";
export default function WatchPage(query) {
  //==============context and query grab===============//
  const context = useContext(AppContext);
  const router = useRouter();
  const { id } = router.query;
  const { price } = router.query;
  const { description } = router.query;
  const { image } = router.query;
  //====================================//

  function cartHandler() {
    //=====cart button number=======//
    var number = context.nameContext;
    number++;
    context.setNameContext(number);
    //=======cart page price setter=======//
    context.setWatchPrice(price);
    //=======cart page description setter=======//
    context.setWatchDescription(description);
    //========cart List============//
    const cartList = context.cartListFinal;
    cartList.push([{ id, price, description, image }]);
    context.setCartListFinal(cartList);
  }
  return (
    <html>
      <Head>
        <title>Augustus Revinci</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nomos.jpg" />
      </Head>
      <body>
        <Navbar></Navbar>
        <section className={styles.selectedWatch}>
          <section></section>
          <div className={styles.watchContainer}>
            <div className={styles.watchImage}>
              <img className={styles.image} src={image} alt="idk"></img>
            </div>
            <section className={styles.selectedWatchInfo}>
              <div className={styles.description}>{description}</div>
              <div className={styles.price}>Price: ${price}</div>
              <button className={styles.buyButton} onClick={cartHandler}>
                ADD TO CART
              </button>
            </section>
          </div>
        </section>
      </body>
    </html>
  );
}
