import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar.js";
import Head from "next/head";
import Link from "next/link";

export default function About() {
  return (
    <html>
      <Head>
        <title>Augustus Revinci</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nomos.jpg" />
      </Head>
      <Navbar />
      <body className={styles.aboutBody}>
        <h1 className={styles.aboutHeader}>SUMMARY</h1>
        <p className={styles.aboutText}>
          This is normally where an about or customer care section would be but
          since this is just a project site I thought I would add some info on
          the project. Obviously the site is not completely fleshed out, I
          decided it would be a wiser decision to practice and learn new skills
          by creating and working on new projects. The idea behind this project
          is to display knowledge of HTML, CSS, JAVASCRIPT, REACT, and NEXTJS
          and specifically: Responsive design for all forms of devices, web
          design concepts, state management, click handlers, modals, flexbox,
          functions, routing, sitewide context, media queries, and many other
          things. I really enjoyed working on this project, and I hope you
          enjoyed it as well. If you would like to work with me or have any
          questions please contact me at PedroCruz6427@outlook.com or checkout
          my github at {""}
          <Link
            className={styles.aboutLink}
            href="https://github.com/PedroCruz6427"
          >
            https://github.com/PedroCruz6427
          </Link>
        </p>
      </body>
    </html>
  );
}
